Better error messages when importing an unavailable .ksy
For example, consider the following spec, which attempts to import a
non-existent .ksy file from local storage:

```ksy
meta:
  id: imports_non_existent_local
  imports:
    - non_existent
```

Old error:

```
Parse error (TypeError): Cannot read properties of null (reading 'indexOf')
Call stack: TypeError: Cannot read properties of null (reading 'indexOf')
    at Parser.cleanup (https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:1220:15)
    at Parser.parse (https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:754:23)
    at Yaml.parse (https://ide.kaitai.io/lib/_npm/yamljs/yaml.js:1817:25)
    at JsImporter.importYaml (https://ide.kaitai.io/js/v1/KaitaiServices.js:51:33)
```

New error:

```
(main): /meta/imports/0:
	error: Error: failed to import spec non_existent.ksy from local storage: file not found
```

Import failures from the remote location "kaitai.io" are now also
handled - consider this spec:

```ksy
meta:
  id: imports_non_existent_remote
  imports:
    - /common/non_existent
```

Old error:

```
Parse error
Call stack: undefined
```

New error:

```
(main): /meta/imports/0:
	error: Error: failed to import spec formats/common/non_existent.ksy from kaitai.io: file not found
```

When the server responds with some other HTTP status code than 404:

```
(main): /meta/imports/0:
	error: Error: failed to import spec formats/common/bcd.ksy from kaitai.io: server responded with HTTP status 500 (Internal Server Error)
```

When you are no longer connected to the internet, but try to import a
remote spec that hasn't been cached locally by the browser:

```
(main): /meta/imports/0:
	error: Error: failed to import spec formats/common/bcd.ksy from kaitai.io: cannot reach the server (message: Failed to fetch), check your internet connection
```